<?php

    include "database_connection.php";

    require './loginSession.php';

    if(isset($_POST['submit'])){
        $firstName = $_POST['firstName'];
        $lastName = $_POST['lastName'];
        $address = $_POST['address'];
        $city = $_POST['city'];
        $pincode = $_POST['pincode'];
        $state = $_POST['state'];
        $phoneNumber = $_POST['phoneNumber'];
        $email = $_POST['email'];
        $paymentMethod = $_POST['paymentMethod'];
        $totalPrice = $_POST['totalPrice'];
    }
    
    $fields = [
        'firstname' => $firstName,
        'lastname' => $lastName,
        'address' => $address,
        'city' => $city,
        'pincode' => $pincode,
        'state' => $state,
        'phoneNumber' => $phoneNumber,
        'email' => $email,
        'paymentMethod' => $paymentMethod
    ];

    $errors = [];

    foreach ($fields as $fieldName => $fieldValue) {
        if (trim($fieldValue) === "") {
            $errors[] = "$fieldName is required.";
        }
    }

    $pincodeLength = strlen((string)$pincode);
    if($pincodeLength != 6){
        $errors[] = "Pincode Is Not Vailed";
    }
    $phoneNumberLength = strlen((string)$phoneNumber);
    if ($phoneNumberLength != 10 ) {
        $errors[] = "Phone Number Is Not Valid";
    }
    
    // Display errors 
    if (!empty($errors)) {

        foreach ($errors as $error) {
            echo "$error <br> ";
        }
    }
    else{
        $firstName = mysqli_real_escape_string($conn, $firstName);
        $lastName = mysqli_real_escape_string($conn, $lastName);
        $address = mysqli_real_escape_string($conn, $address);
        $pincode = mysqli_real_escape_string($conn, $pincode);
        $city = mysqli_real_escape_string($conn, $city);
        $state = mysqli_real_escape_string($conn, $state);
        $phoneNumber = mysqli_real_escape_string($conn, $phoneNumber);
        $email = mysqli_real_escape_string($conn, $email);
        $totalprice = mysqli_real_escape_string($conn, $totalPrice);
        $paymentMethod = mysqli_real_escape_string($conn, $paymentMethod);
    

    $insertQuery = "insert into checkout(firstName,lastName,address,city,pincode,state,phoneNumber,email)
     values ('$firstName','$lastName','$address', '$city', $pincode,'$state', $phoneNumber, '$email')";

    if (mysqli_query($conn,$insertQuery) === TRUE) {
        $email = $_SESSION['email'];
        $selectCartData = "SELECT addtocart.cart_id, addtocart.quantity,addtocart.product_id, products.productName,products.detail, products.price,products.productImage 
                FROM addtocart JOIN products ON addtocart.product_id=products.product_id
                WHERE addtocart.userEmail = '$email'";
            
        $result = mysqli_query($conn,$selectCartData);

        if ($result->num_rows > 0) {
            // Loop through the results
            while ($row = $result->fetch_assoc()) {
                $insertOrder = "INSERT INTO orders(product_id,userEmail, paymentMethod, price) 
                VALUES ('" . $row['product_id'] . "','" . $_SESSION['email'] . "', '$paymentMethod', '" . $row['price'] . "')";  
                if(mysqli_query($conn,$insertOrder) === TRUE){
                    $deleteCartItem = "DELETE FROM addtocart WHERE cart_id = '" . $row['cart_id'] . "' ;";
                    mysqli_query($conn,$deleteCartItem);                 
                }
            }
        } else {
            echo "
            <script>
                alert('No Product Found In Cart');
                window.location.href = '../addToCart.php';
            </script>";
        }

        if($paymentMethod === 'UPI'){        
            $apikey = "rzp_test_RSK7K0PuoUp9b7";
        ?>
        
        <form action="https://www.example.com/success/" method="POST">
        <script
           src="https://checkout.razorpay.com/v1/checkout.js"
            data-key="<?php echo $apikey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
            data-amount="<?php echo $totalPrice * 100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
            data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
            data-id="<?php echo 'OID'.rand(100000,999999).'END'; ?>"// Replace with the order_id generated by you in the backend.
            data-buttontext="Pay with Razorpay"
            data-name="SmartTech Store"
            data-description="Thank you for your purchase at SmartTech Store. We have received your payment "
            data-image="https://example.com/your_logo.jpg"
            data-prefill.name="<?php echo $_POST['firstName']; echo $_POST['lastName']; ?>"
            data-prefill.email="<?php echo $_POST['email']; ?>"
            data-theme.color="#00246b"
        ></script>
        <input type="hidden" custom="Hidden Element" name="hidden"/>
        </form>
        <?php
        }
    }

    else{
        echo "error";
    }
}
    
$conn->close();
?>